export const TOGGLE_SETTINGS_MODAL = 'toggle_settings_modal'
export const TOGGLE_LIST_MODAL = 'toggle_list_modal'
export const UPDATE_MAP_SETTINGS = 'update_map_settings'
export const UPDATE_RADIUS = 'update_radius'
export const UPDATE_CURRENT_LOCATION = 'update_current_location'
export const UPDATE_DAY = 'update_day'
export const UPDATE_MEETINGS = 'update_meetings'